#!/bin/bash
echo 'Searching...'
WIF=`nmcli -t -f ssid dev wifi | rofi -dmenu -p "Available connections"`
PSW=`echo -e '' | rofi -dmenu -p 'Password'`
# NAME=`echo -e '' |dmenu -p 'Wifi ID'`

echo "Connecting..."
nmcli dev wifi connect $WIF password $PSW
